name: Build Clicker APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            zlib1g-dev

      - name: Install Buildozer
        run: |
          pip install --upgrade pip setuptools virtualenv
          pip install buildozer cython==0.29.36

      - name: Configure Buildozer
        run: |
          buildozer init
          cat <<EOT > buildozer.spec
[app]
title = Online Clicker
package.name = onlineclicker
package.domain = org.example
source.dir = .
version = 1.0
requirements = python3,kivy==2.3.0,requests
orientation = portrait
fullscreen = 0
android.arch = arm64-v8a
android.permissions = INTERNET
android.api = 34
android.minapi = 21
EOT

      - name: Build APK
        run: |
          export PATH=$PATH:~/.local/bin/
          buildozer -v android debug
          cp bin/*.apk clicker-app.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: clicker-apk
          path: clicker-app.apk
