name: Build Clicker APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip openjdk-17-jdk \
            python3-pip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libffi-dev libssl-dev \
            git cmake ninja-build \
            python3-venv python3-dev

      - name: Install Buildozer and dependencies
        run: |
          python -m pip install --upgrade pip setuptools virtualenv wheel
          pip install buildozer cython==0.29.36 kivy==2.3.0 requests

      - name: Configure Buildozer
        run: |
          buildozer init
          cat <<EOT > buildozer.spec
          [app]
          title = Online Clicker
          package.name = onlineclicker
          package.domain = org.example
          source.dir = .
          version = 1.0
          requirements = python3,kivy==2.3.0,requests
          orientation = portrait
          fullscreen = 0
          android.archs = arm64-v8a
          android.permissions = INTERNET
          android.minapi = 21
          android.api = 34
          # Используем рекомендованные версии
          android.ndk = 25b
          p4a.branch = master
          android.accept_sdk_license = True
          log_level = 2
          EOT

      - name: Pre-download Android tools
        run: |
          mkdir -p ~/.buildozer/android/platform
          cd ~/.buildozer/android/platform
          
          # Скачиваем NDK напрямую
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip
          mv android-ndk-r25b android-ndk-r25b
          rm android-ndk-r25b-linux.zip
          
          # Устанавливаем переменные окружения
          echo "ANDROID_NDK_HOME=~/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
          echo "NDK_HOME=~/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV

      - name: Build APK
        run: |
          # Устанавливаем переменные для Buildozer
          export ANDROID_SDK_ROOT=~/.buildozer/android/platform/android-sdk
          export ANDROID_NDK_HOME=~/.buildozer/android/platform/android-ndk-r25b
          
          buildozer -v android clean
          buildozer -v android debug
          
          if [ -f bin/*.apk ]; then
            cp bin/*.apk clicker-app.apk
          else
            echo "APK generation failed!"
            echo "Buildozer log:"
            tail -n 200 buildozer.log
            exit 1
          fi

      - name: Verify and optimize APK
        run: |
          if [ -f clicker-app.apk ]; then
            echo "APK generated successfully ($(du -h clicker-app.apk | cut -f1))"
            # Оптимизируем APK
            zipalign -v 4 clicker-app.apk clicker-app-aligned.apk
            mv clicker-app-aligned.apk clicker-app.apk
          else
            exit 1
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: clicker-apk
          path: clicker-app.apk
          if-no-files-found: error
          retention-days: 5
