name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILDOZER_ALLOW_ROOT: 1
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          openjdk-11-jdk \
          python3-pip \
          python3-setuptools \
          git \
          unzip \
          zip \
          libssl-dev \
          libffi-dev \
          libsqlite3-dev \
          autoconf \
          automake \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5 \
          libncurses5-dev \
          libtinfo5
        python3 -m pip install --upgrade pip
        python3 -m pip install buildozer cython

    - name: First Buildozer run to initialize SDK
      run: |
        buildozer android clean || true
        buildozer android debug || true

    - name: Accept Android SDK licenses
      run: |
        export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
        yes | sdkmanager --licenses || true
        yes | sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" || true

    - name: Final Build
      run: buildozer -v android debug

