name: Build Clicker APK

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v4

      - name: Build with Docker
        run: |
          # Создаем временный Dockerfile
          cat <<EOT > Dockerfile
          FROM kivy/buildozer:latest

          # Копируем исходный код
          COPY . /app
          WORKDIR /app

          # Устанавливаем зависимости Python
          RUN pip install requests kivy==2.3.0

          # Создаем buildozer.spec
          RUN echo "\
          [app]\n\
          title = Online Clicker\n\
          package.name = onlineclicker\n\
          package.domain = org.example\n\
          source.dir = .\n\
          version = 1.0\n\
          requirements = python3,kivy==2.3.0,requests\n\
          orientation = portrait\n\
          fullscreen = 0\n\
          android.archs = arm64-v8a\n\
          android.permissions = INTERNET\n\
          android.minapi = 21\n\
          android.api = 34\n\
          " > buildozer.spec

          # Собираем APK
          RUN buildozer android debug
          EOT

          # Собираем и запускаем контейнер
          docker build -t kivy-builder .
          docker run --rm -v $PWD:/host kivy-builder sh -c "cp bin/*.apk /host/clicker-app.apk"

      - name: Verify APK
        run: |
          if [ -f clicker-app.apk ]; then
            echo "APK generated successfully ($(du -h clicker-app.apk | cut -f1))"
          else
            echo "APK generation failed!"
            exit 1
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: clicker-apk
          path: clicker-app.apk
          if-no-files-found: error
          retention-days: 5
