name: Build Clicker APK

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 45
    
    steps:
      - uses: actions/checkout@v4

      - name: Clean existing files
        run: |
          rm -f buildozer.spec
          rm -rf .buildozer bin

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            zlib1g-dev \
            libncurses-dev \
            libtinfo6 \
            cmake \
            libffi-dev \
            libssl-dev \
            git \
            autoconf \
            libtool \
            pkg-config

      - name: Cache Android SDK
        uses: actions/cache@v3
        with:
          path: |
            ~/.buildozer
            ~/.android
          key: ${{ runner.os }}-android-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-android-

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip setuptools virtualenv
          pip install buildozer cython==0.29.36 kivy==2.3.0

      - name: Initialize Buildozer
        run: |
          buildozer init
          [ -f buildozer.spec ] && echo "Buildozer initialized successfully" || exit 1

      - name: Configure Buildozer
        run: |
          cat <<EOT > buildozer.spec
          [app]
          title = Online Clicker
          package.name = onlineclicker
          package.domain = org.example
          source.dir = .
          version = 1.0
          requirements = python3,kivy==2.3.0,requests
          orientation = portrait
          fullscreen = 0
          android.arch = arm64-v8a
          android.permissions = INTERNET
          android.sdk = 34
          android.ndk = 25c
          android.minapi = 21
          android.api = 34
          android.build_tools_version = 34.0.0
          android.sdk_path = $HOME/.buildozer/android/platform/android-sdk
          android.ndk_path = $HOME/.buildozer/android/platform/android-ndk
          p4a.branch = master
          android.accept_sdk_license = True
          EOT

      - name: Accept Android licenses
        run: |
          mkdir -p ~/.android/licenses
          echo "d56f5187479451eabf01fd78e6e452a9cf6d38f9" > ~/.android/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > ~/.android/licenses/android-sdk-preview-license
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > ~/.android/licenses/intel-android-extra-license

      - name: Install Android tools
        run: |
          export PATH=$PATH:$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin
          yes | sdkmanager --install "build-tools;34.0.0" "platform-tools" "platforms;android-34" "cmdline-tools;latest"
          sdkmanager --update

      - name: Build APK
        run: |
          export PATH=$PATH:~/.local/bin/:$HOME/.buildozer/android/platform/android-sdk/platform-tools
          buildozer android clean
          buildozer -v android debug
          find bin/ -name '*.apk' -exec cp {} clicker-app.apk \;

      - name: Verify APK
        run: |
          if [ -f clicker-app.apk ]; then
            echo "APK generated successfully"
            ls -lh clicker-app.apk
          else
            echo "APK generation failed"
            ls -la bin/
            exit 1
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: clicker-apk
          path: clicker-app.apk
          if-no-files-found: error
          retention-days: 5

      - name: Show build logs
        if: always()
        run: |
          echo "### Last 100 lines of build log ###"
          tail -n 100 build.log || true
