name: Build Clicker APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip openjdk-17-jdk \
            python3-pip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libffi-dev libssl-dev \
            git cmake ninja-build \
            python3-venv python3-dev

      - name: Install Buildozer and dependencies
        run: |
          python -m pip install --upgrade pip setuptools virtualenv wheel
          pip install buildozer cython==0.29.36 kivy==2.3.0 requests
          pip install python-for-android

      - name: Configure Buildozer
        run: |
          buildozer init
          cat <<EOT > buildozer.spec
          [app]
          title = Online Clicker
          package.name = onlineclicker
          package.domain = org.example
          source.dir = .
          version = 1.0
          requirements = python3,kivy==2.3.0,requests
          orientation = portrait
          fullscreen = 0
          android.archs = arm64-v8a
          android.permissions = INTERNET
          android.minapi = 21
          android.api = 34
          android.ndk = 25b
          p4a.branch = develop
          android.accept_sdk_license = True
          log_level = 2
          EOT

      - name: Setup Android NDK
        run: |
          mkdir -p ~/.buildozer/android/platform
          cd ~/.buildozer/android/platform
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip
          rm android-ndk-r25b-linux.zip
          echo "ANDROID_NDK_HOME=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV

      - name: Setup Android SDK
        run: |
          mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools
          cd ~/.buildozer/android/platform/android-sdk/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip -d tmp
          mv tmp/cmdline-tools latest
          rm -rf tmp commandlinetools-linux-9477386_latest.zip
          
          yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-34" "build-tools;34.0.0"
          
          echo "ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_ENV

      - name: Setup Python-for-Android
        run: |
          # Create the directory where buildozer expects p4a
          mkdir -p $GITHUB_WORKSPACE/.buildozer/android/platform/python-for-android
          git clone https://github.com/kivy/python-for-android.git $GITHUB_WORKSPACE/.buildozer/android/platform/python-for-android
          cd $GITHUB_WORKSPACE/.buildozer/android/platform/python-for-android
          git checkout develop
          pip install -e .
          
          # Also install in the global site-packages for good measure
          pip install python-for-android

      - name: Build APK
        run: |
          export BUILD_DIR=$GITHUB_WORKSPACE
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          export ANDROID_NDK_HOME=$HOME/.buildozer/android/platform/android-ndk-r25b
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_NDK_HOME
          
          # Ensure p4a is in the correct location
          mkdir -p $BUILD_DIR/.buildozer/android/platform/python-for-android
          [ -d "$BUILD_DIR/.buildozer/android/platform/python-for-android" ] || exit 1
          
          cd $BUILD_DIR
          buildozer -v android clean
          buildozer -v android debug
          
          if ls bin/*.apk 1> /dev/null 2>&1; then
            cp bin/*.apk clicker-app.apk
          else
            echo "APK generation failed!"
            tail -n 200 buildozer.log
            exit 1
          fi

      - name: Optimize APK
        run: |
          if [ -f clicker-app.apk ]; then
            echo "APK size before optimization: $(du -h clicker-app.apk | cut -f1)"
            $HOME/.buildozer/android/platform/android-sdk/build-tools/34.0.0/zipalign -v 4 clicker-app.apk clicker-app-aligned.apk
            mv clicker-app-aligned.apk clicker-app.apk
            echo "APK size after optimization: $(du -h clicker-app.apk | cut -f1)"
          else
            echo "No APK found to optimize!"
            exit 1
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: clicker-apk
          path: clicker-app.apk
          if-no-files-found: error
          retention-days: 5
