name: Build Clicker APK

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 45
    
    steps:
      - uses: actions/checkout@v4

      - name: Clean workspace
        run: |
          rm -f buildozer.spec
          rm -rf .buildozer bin

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            zlib1g-dev \
            libncurses-dev \
            libtinfo6 \
            cmake \
            libffi-dev \
            libssl-dev \
            git \
            autoconf \
            libtool \
            pkg-config \
            wget

      - name: Install Buildozer
        run: |
          pip install --upgrade pip setuptools virtualenv
          pip install buildozer cython==0.29.36 kivy==2.3.0

      - name: Initialize Buildozer
        run: |
          buildozer init
          [ -f buildozer.spec ] || exit 1

      - name: Configure Buildozer
        run: |
          cat <<EOT > buildozer.spec
          [app]
          title = Online Clicker
          package.name = onlineclicker
          package.domain = org.example
          source.dir = .
          version = 1.0
          requirements = python3,kivy==2.3.0,requests
          orientation = portrait
          fullscreen = 0
          android.arch = arm64-v8a
          android.permissions = INTERNET
          android.sdk = 34
          android.ndk = 25c
          android.minapi = 21
          android.api = 34
          android.build_tools_version = 34.0.0
          p4a.branch = master
          android.accept_sdk_license = True
          EOT

      - name: Install Android Command Line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin

      - name: Accept licenses and install SDK
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "build-tools;34.0.0" "platforms;android-34"
          sdkmanager --update

      - name: Build APK
        run: |
          export PATH=$PATH:$HOME/android-sdk/platform-tools
          buildozer android clean
          buildozer -v android debug
          find bin/ -name '*.apk' -exec cp {} clicker-app.apk \;

      - name: Verify APK
        run: |
          if [ -f clicker-app.apk ]; then
            echo "APK generated successfully ($(du -h clicker-app.apk | cut -f1))"
          else
            echo "APK generation failed!"
            echo "Buildozer log:"
            tail -n 100 buildozer.log || true
            exit 1
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: clicker-apk
          path: clicker-app.apk
          if-no-files-found: error
          retention-days: 5
