name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-17-jdk
        pip install buildozer
    - name: Build APK
      run: |
        buildozer -v android debug
        cp bin/*.apk clicker-app.apk
    - uses: actions/upload-artifact@v3
      with:
        name: clicker-apk
        path: clicker-app.apk
