name: Build Clicker APK

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip openjdk-17-jdk \
            python3-pip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libffi-dev libssl-dev

      - name: Install Buildozer
        run: |
          pip install --upgrade pip setuptools virtualenv
          pip install buildozer cython==0.29.36 kivy==2.3.0

      - name: Configure Buildozer
        run: |
          buildozer init
          cat <<EOT > buildozer.spec
          [app]
          title = Online Clicker
          package.name = onlineclicker
          package.domain = org.example
          source.dir = .
          version = 1.0
          requirements = python3,kivy==2.3.0,requests
          orientation = portrait
          fullscreen = 0
          android.archs = arm64-v8a
          android.permissions = INTERNET
          android.minapi = 21
          android.api = 34
                    android.sdk = 34
          android.ndk = 25c
          EOT

      - name: Build APK
        run: |
          buildozer -v android debug
          find bin/ -name '*.apk' -exec cp {} clicker-app.apk \;

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: clicker-apk
          path: clicker-app.apk
          if-no-files-found: error
          retention-days: 5
