name: Build APK with Buildozer

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  BUILDOZER_ALLOW_ROOT: 1
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8
  ANDROID_HOME: $HOME/android-sdk
  ANDROID_NDK_HOME: $HOME/android-sdk/ndk/r25b
  PATH: $HOME/.local/bin:$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$HOME/android-sdk/build-tools/33.0.2:$PATH

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          tar \
          openjdk-11-jdk \
          python3-pip \
          python3-setuptools \
          git \
          zip \
          unzip \
          libssl-dev \
          libffi-dev \
          libsqlite3-dev \
          autoconf \
          automake \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5 \
          libncurses5-dev \
          libtinfo5 \
          wget

        pip install --upgrade pip
        pip install --user cython buildozer

    - name: Install Android SDK + Build Tools 33
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools/tmp
        mv $ANDROID_HOME/cmdline-tools/tmp/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        rm -rf $ANDROID_HOME/cmdline-tools/tmp
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME \
          "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Install Android NDK manually
      run: |
        mkdir -p $ANDROID_HOME/ndk
        cd $ANDROID_HOME/ndk
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -O ndk.zip
        unzip ndk.zip
        mv android-ndk-r25b r25b

    - name: Build APK
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export ANDROID_NDK_HOME=$HOME/android-sdk/ndk/r25b
        export PATH=$HOME/.local/bin:$PATH
        buildozer android debug
