name: Build Clicker APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip openjdk-17-jdk \
            python3-pip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libffi-dev libssl-dev \
            git cmake ninja-build \
            python3-venv python3-dev

      - name: Install Buildozer and dependencies
        run: |
          python -m pip install --upgrade pip setuptools virtualenv wheel
          pip install buildozer cython==0.29.36 kivy==2.3.0 requests
          pip install python-for-android

      - name: Configure Buildozer
        run: |
          buildozer init
          cat <<EOT > buildozer.spec
          [app]
          title = Online Clicker
          package.name = onlineclicker
          package.domain = org.example
          source.dir = .
          version = 1.0
          requirements = python3,kivy==2.3.0,requests
          orientation = portrait
          fullscreen = 0
          android.archs = arm64-v8a
          android.permissions = INTERNET
          android.minapi = 21
          android.api = 34
          android.ndk = 25b
          p4a.branch = develop
          android.accept_sdk_license = True
          log_level = 2
          EOT

      - name: Setup Android environment
        run: |
          # Create necessary directories
          mkdir -p ~/.buildozer/android/platform
          
          # Download and extract NDK
          cd ~/.buildozer/android/platform
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip
          rm android-ndk-r25b-linux.zip
          
          # Setup SDK
          mkdir -p ~/.buildozer/android/platform/android-sdk
          cd ~/.buildozer/android/platform/android-sdk
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip
          rm commandlinetools-linux-9477386_latest.zip
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/* cmdline-tools/latest/
          
          # Accept licenses and install components
          yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-34" "build-tools;34.0.0"
          
          # Set environment variables
          echo "ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV

      - name: Initialize python-for-android
        run: |
          # Create p4a directory structure
          mkdir -p ~/.buildozer/android/platform/python-for-android
          git clone https://github.com/kivy/python-for-android.git ~/.buildozer/android/platform/python-for-android
          cd ~/.buildozer/android/platform/python-for-android
          git checkout develop
          pip install -e .

      - name: Build APK
        run: |
          # Set buildozer environment
          export BUILD_DIR=$GITHUB_WORKSPACE
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          export ANDROID_NDK_HOME=$HOME/.buildozer/android/platform/android-ndk-r25b
          
          # Build the APK
          cd $BUILD_DIR
          buildozer -v android clean
          buildozer -v android debug
          
          # Check if APK was generated
          if ls bin/*.apk 1> /dev/null 2>&1; then
            cp bin/*.apk clicker-app.apk
          else
            echo "APK generation failed!"
            echo "Buildozer log:"
            tail -n 200 buildozer.log
            exit 1
          fi

      - name: Verify and optimize APK
        run: |
          if [ -f clicker-app.apk ]; then
            echo "APK generated successfully ($(du -h clicker-app.apk | cut -f1))"
            # Optimize APK
            $HOME/.buildozer/android/platform/android-sdk/build-tools/34.0.0/zipalign -v 4 clicker-app.apk clicker-app-aligned.apk
            mv clicker-app-aligned.apk clicker-app.apk
          else
            echo "No APK found to optimize!"
            exit 1
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: clicker-apk
          path: clicker-app.apk
          if-no-files-found: error
          retention-days: 5
