name: Build APK with Buildozer

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  BUILDOZER_ALLOW_ROOT: 1
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies and set Java 17
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          openjdk-17-jdk \
          python3-pip \
          python3-setuptools \
          git \
          zip \
          unzip \
          libssl-dev \
          libffi-dev \
          libsqlite3-dev \
          autoconf \
          automake \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5 \
          libncurses5-dev \
          libtinfo5 \
          wget

        sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk-amd64/bin/java 1710
        sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac 1710
        sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
        sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac

        pip install --upgrade pip
        pip install cython buildozer

    - name: Set JAVA_HOME
      run: echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))" >> $GITHUB_ENV

    - name: Install Android SDK Build-tools and NDK manually
      run: |
        mkdir -p $HOME/android-sdk

        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
        rm cmdline-tools.zip

        if [ -d "$HOME/android-sdk/cmdline-tools/cmdline-tools" ]; then
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
          rm -rf $HOME/android-sdk/cmdline-tools/cmdline-tools
        else
          mv $HOME/android-sdk/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        fi

        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.2"

        # Принудительное принятие всех лицензий
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses

        # Скачиваем NDK r25b
        mkdir -p $HOME/.buildozer/android/platform
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -O android-ndk.zip
        unzip -q android-ndk.zip -d $HOME/.buildozer/android/platform/
        rm android-ndk.zip

        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/platform-tools:$HOME/android-sdk/build-tools/33.0.2:$PATH" >> $GITHUB_ENV

    - name: Build APK
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/33.0.2:$PATH
        buildozer -v android debug
