name: Build Clicker APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # Используем Ubuntu 22.04 для лучшей совместимости
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9  # Более стабильная версия для Kivy
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip openjdk-17-jdk \
            python3-pip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libffi-dev libssl-dev \
            git cmake ninja-build \
            python3-venv python3-dev

      - name: Install Buildozer and dependencies
        run: |
          python -m pip install --upgrade pip setuptools virtualenv wheel
          pip install buildozer cython==0.29.36 kivy==2.3.0 requests

      - name: Configure Buildozer
        run: |
          buildozer init
          cat <<EOT > buildozer.spec
          [app]
          title = Online Clicker
          package.name = onlineclicker
          package.domain = org.example
          source.dir = .
          version = 1.0
          requirements = python3,kivy==2.3.0,requests
          orientation = portrait
          fullscreen = 0
          android.archs = arm64-v8a
          android.permissions = INTERNET
          android.minapi = 21
          android.api = 34
          android.sdk = 30  # Более стабильная версия SDK
          android.ndk = 23b  # Проверенная версия NDK
          p4a.branch = master
          android.accept_sdk_license = True
          log_level = 2
          EOT

      - name: Build APK (with retry)
        run: |
          set +e
          for i in {1..3}; do
            echo "Attempt $i/3"
            buildozer -v android clean
            buildozer -v android debug
            if [ -f bin/*.apk ]; then
              cp bin/*.apk clicker-app.apk
              exit 0
            fi
            echo "Build failed, retrying..."
            sleep 10
          done
          exit 1

      - name: Verify APK
        run: |
          if [ -f clicker-app.apk ]; then
            echo "APK generated successfully ($(du -h clicker-app.apk | cut -f1))"
            # Оптимизируем APK
            zipalign -v 4 clicker-app.apk clicker-app-aligned.apk
            mv clicker-app-aligned.apk clicker-app.apk
          else
            echo "APK generation failed!"
            echo "Buildozer log:"
            tail -n 200 buildozer.log
            exit 1
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: clicker-apk
          path: clicker-app.apk
          if-no-files-found: error
          retention-days: 5
