name: Build Clicker APK

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            zlib1g-dev \
            libncurses6-dev \
            libncursesw6-dev \
            libtinfo6 \
            cmake \
            libffi-dev \
            libssl-dev

      - name: Cache Android SDK
        uses: actions/cache@v3
        with:
          path: |
            ~/.buildozer
            ~/.android
          key: ${{ runner.os }}-android-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-android-

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip setuptools virtualenv
          pip install buildozer cython==0.29.36

      - name: Accept Android licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          mkdir -p ~/.android/licenses
          echo "d56f5187479451eabf01fd78e6e452a9cf6d38f9" > ~/.android/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > ~/.android/licenses/android-sdk-preview-license
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > ~/.android/licenses/intel-android-extra-license

      - name: Install Android tools
        run: |
          export PATH=$PATH:$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin
          yes | sdkmanager --install "build-tools;34.0.0" "platform-tools" "platforms;android-34" "cmdline-tools;latest"
          sdkmanager --update

      - name: Build APK
        run: |
          export PATH=$PATH:~/.local/bin/:$HOME/.buildozer/android/platform/android-sdk/platform-tools
          buildozer android clean
          buildozer -v android debug 2>&1 | tee build.log
          cp bin/*.apk clicker-app.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: clicker-apk
          path: clicker-app.apk
          retention-days: 5

      - name: Check build log
        if: ${{ always() }}
        run: |
          tail -n 100 build.log || true
          ls -la bin/ || true
